- name: Publish the Lastest Germanium Selector Builder
  gather_facts: False
  hosts: ciplogic
  tasks:
    - name: Create the germaniumsb release folder
      become: True
      file:
        state: directory
        path: /opt/www/germaniumhq_get/germaniumsb

    - name: Upload the linux binary file.
      become: True
      synchronize:
        src: ../_archive/germaniumsb
        dest: /opt/www/germaniumhq_get/germaniumsb/germaniumsb_upload

    - name: Upload the windows binary file.
      become: True
      synchronize:
        src: ../_archive/germaniumsb.exe
        dest: /opt/www/germaniumhq_get/germaniumsb/germaniumsb_upload.exe

    - name: Rename the binaries.
      become: True
      shell: |
        mv -f /opt/www/germaniumhq_get/germaniumsb/germaniumsb_upload /opt/www/germaniumhq_get/germaniumsb/germaniumsb
        mv -f /opt/www/germaniumhq_get/germaniumsb/germaniumsb_upload.exe /opt/www/germaniumhq_get/germaniumsb/germaniumsb.exe
        chmod 660 /opt/www/germaniumhq_get/germaniumsb/germaniumsb
        chown -R 100:101 /opt/www/germaniumhq_get/germaniumsb/

