# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'germaniumsb/MainWindow.ui',
# licensing of 'germaniumsb/MainWindow.ui' applies.
#
# Created: Sun Sep 30 05:05:53 2018
#      by: pyside2-uic  running on PySide2 5.11.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 608)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.browserLabel = QtWidgets.QLabel(self.centralwidget)
        self.browserLabel.setObjectName("browserLabel")
        self.horizontalLayout.addWidget(self.browserLabel)
        self.browserCombo = QtWidgets.QComboBox(self.centralwidget)
        self.browserCombo.setObjectName("browserCombo")
        self.horizontalLayout.addWidget(self.browserCombo)
        self.startBrowserButton = QtWidgets.QPushButton(self.centralwidget)
        self.startBrowserButton.setObjectName("startBrowserButton")
        self.horizontalLayout.addWidget(self.startBrowserButton)
        self.stopBrowserButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopBrowserButton.setObjectName("stopBrowserButton")
        self.horizontalLayout.addWidget(self.stopBrowserButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.liveButton = QtWidgets.QPushButton(self.centralwidget)
        self.liveButton.setCheckable(True)
        self.liveButton.setChecked(True)
        self.liveButton.setFlat(False)
        self.liveButton.setObjectName("liveButton")
        self.horizontalLayout.addWidget(self.liveButton)
        self.highlightElementButton = QtWidgets.QPushButton(self.centralwidget)
        self.highlightElementButton.setObjectName("highlightElementButton")
        self.horizontalLayout.addWidget(self.highlightElementButton)
        self.pickElementButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickElementButton.sizePolicy().hasHeightForWidth())
        self.pickElementButton.setSizePolicy(sizePolicy)
        self.pickElementButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.pickElementButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.pickElementButton.setObjectName("pickElementButton")
        self.horizontalLayout.addWidget(self.pickElementButton)
        self.cancelPickButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelPickButton.setObjectName("cancelPickButton")
        self.horizontalLayout.addWidget(self.cancelPickButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.codeEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.codeEdit.setFont(font)
        self.codeEdit.setPlainText("")
        self.codeEdit.setObjectName("codeEdit")
        self.gridLayout.addWidget(self.codeEdit, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuExecute = QtWidgets.QMenu(self.menubar)
        self.menuExecute.setObjectName("menuExecute")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHighlight = QtWidgets.QAction(MainWindow)
        self.actionHighlight.setEnabled(False)
        self.actionHighlight.setObjectName("actionHighlight")
        self.actionPick = QtWidgets.QAction(MainWindow)
        self.actionPick.setEnabled(False)
        self.actionPick.setObjectName("actionPick")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionSwitch_Selector_Mode = QtWidgets.QAction(MainWindow)
        self.actionSwitch_Selector_Mode.setObjectName("actionSwitch_Selector_Mode")
        self.actionGermaniumHelp = QtWidgets.QAction(MainWindow)
        self.actionGermaniumHelp.setObjectName("actionGermaniumHelp")
        self.menuHelp.addAction(self.actionGermaniumHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutQt)
        self.menuExecute.addAction(self.actionHighlight)
        self.menuExecute.addAction(self.actionPick)
        self.menuExecute.addSeparator()
        self.menubar.addAction(self.menuExecute.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Germanium Selector Builder v2.0.5", None, -1))
        self.browserLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Browser:", None, -1))
        self.startBrowserButton.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.stopBrowserButton.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.liveButton.setText(QtWidgets.QApplication.translate("MainWindow", "Live", None, -1))
        self.highlightElementButton.setText(QtWidgets.QApplication.translate("MainWindow", "Highlight", None, -1))
        self.pickElementButton.setText(QtWidgets.QApplication.translate("MainWindow", "Pick", None, -1))
        self.cancelPickButton.setText(QtWidgets.QApplication.translate("MainWindow", "Cancel Pick", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "He&lp", None, -1))
        self.menuExecute.setTitle(QtWidgets.QApplication.translate("MainWindow", "E&xecute", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "&About", None, -1))
        self.actionHighlight.setText(QtWidgets.QApplication.translate("MainWindow", "&Highlight", None, -1))
        self.actionPick.setText(QtWidgets.QApplication.translate("MainWindow", "&Pick", None, -1))
        self.actionAboutQt.setText(QtWidgets.QApplication.translate("MainWindow", "About &Qt", None, -1))
        self.actionSwitch_Selector_Mode.setText(QtWidgets.QApplication.translate("MainWindow", "Switch Selector Mode", None, -1))
        self.actionGermaniumHelp.setText(QtWidgets.QApplication.translate("MainWindow", "&GermaniumSB Help", None, -1))

